name: CICD

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: This is the environment calue where workflow run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging 

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Take code
        run: echo "Git clone"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        run: echo "Docker build"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: echo "Docker ps"

  deploy:
    if: inputs.environment == 'dev'
    needs: [test,code,build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Docker run"
