# This is workflow name
name: Hello

on:
  workflow_dispatch: 

#These are jobs inside the workflow 
jobs:
  greet:
    runs-on: ubuntu-latest 
    steps:
      - name: Say Hello
        run: echo "Hello"
      - name: Say User
        run: echo "$USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: versions of docker and python
        run: docker --version && python --version
